'use strict';
const {
  Model
} = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class blanko_full extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  blanko_full.init({
    hiv_status: DataTypes.BOOLEAN,
    hiv_date: DataTypes.DATE,
    tbc_status: DataTypes.BOOLEAN,
    tbc_date: DataTypes.DATE,
    malaria_status: DataTypes.BOOLEAN,
    malaria_date: DataTypes.DATE,
    leprosy_status: DataTypes.BOOLEAN,
    leprosy_date: DataTypes.DATE,
    std_status: DataTypes.BOOLEAN,
    std_date: DataTypes.DATE,
    asma_status: DataTypes.BOOLEAN,
    asma_date: DataTypes.DATE,
    hd_status: DataTypes.BOOLEAN,
    hd_date: DataTypes.DATE,
    hpts_status: DataTypes.BOOLEAN,
    hpts_date: DataTypes.DATE,
    dbm_status: DataTypes.BOOLEAN,
    dbm_date: DataTypes.DATE,
    ptu_status: DataTypes.BOOLEAN,
    ptu_date: DataTypes.DATE,
    kidney_status: DataTypes.BOOLEAN,
    kidney_date: DataTypes.DATE,
    cancer_status: DataTypes.BOOLEAN,
    cancer_date: DataTypes.DATE,
    epylepsy_status: DataTypes.BOOLEAN,
    epylepsy_date: DataTypes.DATE,
    psin_status: DataTypes.BOOLEAN,
    psin_date: DataTypes.DATE,
    hepo_status: DataTypes.BOOLEAN,
    hepo_date: DataTypes.DATE,
    hpts_status: DataTypes.BOOLEAN,
    hpts_date: DataTypes.DATE,
    other_status: DataTypes.BOOLEAN,
    other_date: DataTypes.DATE,
    snf_status: DataTypes.BOOLEAN,
    nyd_status: DataTypes.BOOLEAN,
    dbj_status: DataTypes.BOOLEAN,
    pbk_status: DataTypes.BOOLEAN,
    rspks_status: DataTypes.BOOLEAN,
    hmp_status: DataTypes.BOOLEAN,
    ksm_status: DataTypes.BOOLEAN,
    rhb_sbk_status: DataTypes.BOOLEAN,
    gskl_status: DataTypes.BOOLEAN,
    kcuv_status: DataTypes.BOOLEAN,
    nsm_status: DataTypes.BOOLEAN,
    mpbw_status: DataTypes.BOOLEAN,
    rkk_status: DataTypes.BOOLEAN,
    pkln_status: DataTypes.BOOLEAN,
    dfab_status: DataTypes.BOOLEAN,
    anemia_status: DataTypes.BOOLEAN,
    pkn_status: DataTypes.BOOLEAN,
    tb_mt_kanan: DataTypes.BOOLEAN,
    db_mt_kanan: DataTypes.BOOLEAN,
    tgp_kanan: DataTypes.BOOLEAN,
    kbw_kanan: DataTypes.BOOLEAN,
    tb_mt_kiri: DataTypes.BOOLEAN,
    db_mt_kiri: DataTypes.BOOLEAN,
    tgp_kiri: DataTypes.BOOLEAN,
    kbw_kiri: DataTypes.BOOLEAN,
    ukj_status: DataTypes.BOOLEAN,
    saj_status: DataTypes.BOOLEAN,
    tl_jantung: DataTypes.STRING,
    sp_status: DataTypes.BOOLEAN,
    tl_sp: DataTypes.STRING,
    hati_status: DataTypes.BOOLEAN,
    limpa_status: DataTypes.BOOLEAN,
    ginjal_status: DataTypes.BOOLEAN,
    tl_sp_status: DataTypes.BOOLEAN,
    tl_sp: DataTypes.STRING,
    pr_sp_status: DataTypes.BOOLEAN,
    smu_status: DataTypes.BOOLEAN,
    berbicara_status: DataTypes.BOOLEAN,
    fk_status: DataTypes.BOOLEAN,
    usp_status: DataTypes.BOOLEAN,
    km_status: DataTypes.BOOLEAN,
    sensorik_status: DataTypes.BOOLEAN,
    reflek_status: DataTypes.BOOLEAN,
    psg_pbn_status: DataTypes.BOOLEAN,
    luka_status: DataTypes.BOOLEAN,
    elisa_status: DataTypes.BOOLEAN,
    hbsag_status: DataTypes.BOOLEAN,
    hct_status: DataTypes.BOOLEAN,
    vdrl_tpha_status: DataTypes.BOOLEAN,
    pama_status: DataTypes.BOOLEAN,
    pafil_status: DataTypes.BOOLEAN,
    ck_status: DataTypes.BOOLEAN,
    cxray_report: DataTypes.STRING,
    sptm_afb_status: DataTypes.BOOLEAN,
    serum_krtnn: DataTypes.STRING,
    warna_urin: DataTypes.STRING,
    gravitasi_spesifik: DataTypes.STRING,
    gula_status: DataTypes.BOOLEAN,
    albumin_status: DataTypes.BOOLEAN,
    pm_miros: DataTypes.STRING,
    oga_status: DataTypes.BOOLEAN,
    kehamilan_status: DataTypes.BOOLEAN,
    urus_status: DataTypes.BOOLEAN,
    stm_hiv_status: DataTypes.BOOLEAN,
    stm_tbc_status: DataTypes.BOOLEAN,
    stm_malaria_status: DataTypes.BOOLEAN,
    stm_kusta_status: DataTypes.BOOLEAN,
    stm_pms_status: DataTypes.BOOLEAN,
    stm_hpb_status: DataTypes.BOOLEAN,
    stm_hpc_status: DataTypes.BOOLEAN,
    stm_filariasis_status: DataTypes.BOOLEAN,
    gpu_status: DataTypes.BOOLEAN,
    stm_pkl_status: DataTypes.BOOLEAN,
    urine_oka_status: DataTypes.BOOLEAN,
    dsh_status: DataTypes.BOOLEAN,
    sehat_bekerja_status: DataTypes.BOOLEAN,
    rekom_status: DataTypes.BOOLEAN,
    rekom_alasan: DataTypes.STRING,
    dokter: DataTypes.STRING,
    masa_berlaku: DataTypes.DATE,
    sampai_dengan: DataTypes.DATE
  }, {
    sequelize,
    modelName: 'blanko_full',
  });
  return blanko_full;
};